
version: "3.6"

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local

services:
  jupyterlab:
    image: pavansrivathsa/jupyterlab
    hostname: JUPYTERLAB
    container_name: jupyterlab
    ports:
      - "4888:4888"
      - "4040:4040"
      - "8050:8050"
    volumes:
      - shared-workspace:/opt/workspace

  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.5.1'
    hostname: ZOOKEEPER
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  nifi:
    image: apache/nifi:1.14.0
    hostname: NiFi
    container_name: nifi
    ports:
      - "2080:2080"
    environment:
      NIFI_WEB_HTTP_PORT: 2080
      NIFI_CLUSTER_IS_NODE: "true"
      NIFI_CLUSTER_NODE_PROTOCOL_PORT: 2084
      NIFI_ZK_CONNECT_STRING: zookeeper:2181
      NIFI_ELECTION_MAX_WAIT: "1 min"
      NIFI_SENSITIVE_PROPS_KEY: vvvvvvvvvvvv
    volumes:
      - shared-workspace:/opt/workspace/nifi